version: '3.8'


services:
  db:
    image: postgres:16-alpine
    restart: no
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: kchat



