server:
  port: 8444

spring:
  application:
    name: KChat Application
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    username: root
    password: admin123
    url: jdbc:postgresql://localhost:5435/kchat
